name: "📁 Техническая задача / Meta issue"
description: "Внутренний шаблон для создателя сборки и модераторов"
title: "[Meta]: "
labels: ["meta"]
body:
  - type: markdown
    attributes:
      value: |
        ### 📁 Внутренняя техническая задача проекта Ultimate Optimization (Доступ ограничен)
  - type: textarea
    id: meta_info
    attributes:
      label: "Технические подробности девелоперской задачи / Details"
      placeholder: "Перевод сборки на новую версию Minecraft 1.21.x и глобальное тестирование стабильности FPS..."
    validations:
      required: true
  - type: checkboxes
    id: user_agreement_meta
    attributes:
      label: "⚖️ Ограничение доступа / Developer Access Only"
      options:
        - label: "Я являюсь разработчиком/модератором сборки Ultimate Optimization или создатель проекта лично попросил меня создать эту техническую задачу / Developer access confirmed"
          required: true
