name: "⚙️ Изменение настроек / Setting change"
description: "Предложите изменить конфиг, горячие клавиши или дефолтные настройки модов для лучшего FPS"
title: "[Setting Change]: "
labels: ["config"]
body:
  - type: markdown
    attributes:
      value: |
        ### ⚙️ Изменение конфигурации Ultimate Optimization / Config changes
  - type: textarea
    id: change_what
    attributes:
      label: "1. Какие настройки нужно изменить по умолчанию? / What configuration should be changed?"
      placeholder: "Отключить мягкое освещение в настройках графики, изменить дистанцию симуляции на 6 чанков..."
    validations:
      required: true
  - type: textarea
    id: change_why
    attributes:
      label: "2. Почему? / Why?"
      placeholder: "Потому что это дает огромный прирост производительности (+15-20 FPS) на старых видеокартах и Xeon-системах..."
    validations:
      required: true
  - type: dropdown
    id: config_os
    attributes:
      label: "3. Операционная система / Operating System"
      options:
        - "🪟 Windows 10 / 11"
        - "🐧 Linux"
        - "🍏 MacOS"
        - "📱 PojavLauncher"
        - "❓ Другая ОС"
    validations:
      required: true
  - type: checkboxes
    id: user_agreement_config
    attributes:
      label: "⚖️ Пользовательское соглашение / User Agreement"
      options:
        - label: "Я гарантирую, что предложенное изменение настроек действительно повышает общую производительность (FPS) или исправляет конфликты управления / I agree to the terms"
          required: true
